#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

/**
 * Laravel 13 — Artisan CLI Entry Point
 */

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

/** @var \Illuminate\Foundation\Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
